ontoproject/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from ontospect import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    # point the root URLconf at the mysample.urls module
    url(r'^ontospect/', include('ontospect.urls')),
    url(r'^admin/', admin.site.urls),
]

ontospect/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'ontospect'
urlpatterns = [
    # ex: /mysample/
    url(r'^$', views.index),
    url(r'^extractors', views.extractors, name='extractors'),
    url(r'^getFileList', views.getFileList, name='getFileList'),
    url(r'^verbalize', views.verbalize, name='verbalize'),
    url(r'^upload', views.upload, name='upload'),
    url(r'^clean_temp_files', views.clean_temp_files, name='clean_temp_files'),
]

ontospect/models.py
from django.db import models

# Create your models here.

ontospect/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
import os
import ontospy
from ontospect.extractor.sensor_extractor import SensorExtractor
from ontospect.extractor.actuator_extractor import ActuatorExtractor
from ontospect.extractor.rule_extractor import RuleExtractor
from ontospect.transform.transform import Transfromer
import json
from antlr4 import *
from ontospect.ruleml_parser.RULEMLParser import RULEMLParser
from ontospect.ruleml_parser.RULEMLLexer import RULEMLLexer
from ontospect.verbalizer.ruleml_verbalizer import RULEMLVerbalizer
import shutil


# Create your views here.
# @csrf_exempt
def index(request):
    return render(request, 'index.html')

def extractors(request):
    onto = request.POST.get('onto_url')
    uniqueid = request.POST.get('uid')
    print(onto)
    model = ontospy.Ontospy(onto, verbose=True)
    sensor_ssn = SensorExtractor(model).get_ssn_sensors()
    sensor_sosa = SensorExtractor(model).get_sosa_sensors()
    sensor_diy = SensorExtractor(model).get_diy_sensors(sensor_ssn, sensor_sosa)
    actuator_sosa = ActuatorExtractor(model).get_sosa_actuators()
    actuator_diy = ActuatorExtractor(model).get_diy_actuators(actuator_sosa)
    sensor_ssn_result = iri_post_process(sensor_ssn)
    sensor_sosa_result = iri_post_process(sensor_sosa)
    sensor_diy_result = iri_post_process(sensor_diy)
    actuator_sosa_result = iri_post_process(actuator_sosa)
    actuator_diy_result = iri_post_process(actuator_diy)
    RuleExtractor(model).start(uniqueid)
    response = HttpResponse()
    response['Content-Type'] = "application/json"
    response.write(json.dumps({'sensorSSN':sensor_ssn_result, 'sensorSOSA':sensor_sosa_result, 'sensorDIY':sensor_diy_result, 'actuatorSOSA':actuator_sosa_result, 'actuatorDIY':actuator_diy_result}))
    return response
# @csrf_exempt
def getFileList(request):
    uniqueid = request.POST.get('uid')
    Transfromer().transform(uniqueid)
    path = r"ontospect/data/transformed/" + uniqueid + "/"
    files = os.listdir(path)
    return HttpResponse(json.dumps(files), content_type='application/json')

def verbalize(request):
    uniqueid = request.POST.get('uid')
    path = r"ontospect/data/transformed/" + uniqueid + "/"
    file = request.POST.get('filename')
    input = FileStream(path + file, encoding='utf-8')
    lexer = RULEMLLexer(input)
    stream = CommonTokenStream(lexer)
    parser = RULEMLParser(stream)
    tree = parser.ruleMLDoc()
    visitor = RULEMLVerbalizer()
    visitor.visit(tree)
    entry = visitor.atom_slasher()
    return HttpResponse(json.dumps(entry), content_type='application/json')

# @csrf_exempt
def upload(request):
    if request.method == "POST":
        file_obj = request.FILES.get('file')
        uniqueid = request.POST.get('uid')
        print("upload name：", file_obj.name)
        print("upload size：", file_obj.size)
        # shutil.rmtree(r'ontospect/data/upload/' + uniqueid + '/', ignore_errors=True)
        os.mkdir(r'ontospect/data/upload/'+ uniqueid + '/')
        filepath = os.path.join(r"ontospect/data/upload/" + uniqueid + "/", file_obj.name)
        f = open(filepath, 'wb')
        for line in file_obj.chunks():
            f.write(line)
        f.close()
        return HttpResponse(json.dumps(filepath), content_type='application/json')

def clean_temp_files(request):
    uniqueid = request.POST.get('uid')
    uploadpath = r'ontospect/data/upload/' + uniqueid
    if os.path.exists(uploadpath):
        shutil.rmtree(uploadpath)
    preprocesspath = r'ontospect/data/preprocessed/' + uniqueid
    if os.path.exists(preprocesspath):
        shutil.rmtree(preprocesspath)
    transformpath = r'ontospect/data/transformed/' + uniqueid
    if os.path.exists(transformpath):
        shutil.rmtree(transformpath)
    return HttpResponse("Done")

def iri_post_process(list):
    output = []
    for i in list:
        item = str(i)
        iri = item.split("*")[1]
        if len(iri.split('#')) > 1:
            name = iri.split('#')[-1]
        else:
            name = iri.split('/')[-1]
        output_item = [name, iri]
        output.append(output_item)
        # print(name)
    print(output)
    return output

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>ontospect - Start Understanding Ontologies</title>

    {% load static %}
  <link REL="SHORTCUT ICON" HREF="{% static "img/favicon.ico" %}"/>
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Merriweather:300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'vendor/fontawesome-free/css/all.min.css' %}">

  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static 'css/coming-soon.css' %}">

   <!-- jquery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %} "></script>
    <script type="text/javascript">
        var extractorsUrl = "{% url "ontospect:extractors" %}";
        var filelistUrl = "{% url "ontospect:getFileList" %}";
        var verbalizeUrl = "{% url "ontospect:verbalize" %}";
        var uploadUrl = "{% url "ontospect:upload" %}";
        var cleanUrl = "{% url "ontospect:clean_temp_files" %}";
    </script>
    <script src="{% static 'js/ontospect.js' %} "></script>


</head>

<body>

{#  <div class="overlay"></div>#}
  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
    <source src="{% static 'mp4/bg.mp4' %}" type="video/mp4">
  </video>

{#------------------Result Page----------------#}
<div class="container-fluid content" id="result-area" style="display: none">
    <div class="row">
    <div class="header col-md-12">
    <div align="left"><img src={% static 'img/logo_header.png' %} height="85" width="300"></div>
    </div>
    <div class="bar col-md-12"></div>
    </div>
    <div class="row">
            {#list title#}
            <div class="list-title col-md-3 text-white py-5 py-md-0">
            <h5 class="list-group-item" id="sensor_title">Sensor<i class="fas fa-cog fa-spin float-right"></i></h5>
            </div>
            <div class="list-title col-md-3 text-white py-5 py-md-0" >
            <h5 class="list-group-item" id="actuator_title">Actuator<i class="fas fa-cog fa-spin float-right"></i></h5>
            </div>
            <div class="list-title col-md-6 text-white py-5 py-md-0" >
             <h5 class="list-group-item" id="rule_count">Logical Rule</h5>
            </div>
    </div>
  <div class="row">
    {#Sensor List#}
    <div class="list-area col-md-3 text-white py-5 py-md-0 pre-scrollable loading-1" id="sensor_div">
    <ul class="list-group" id="ssn_sensor_list" style="display: none">
    <li class="list-group-item" id="ssn_sensor_count" style="text-align: center"></li>
    </ul>
    <ul class="list-group" id="sosa_sensor_list" style="display: none">
    <li class="list-group-item" id="sosa_sensor_count" style="text-align: center"></li>
    </ul>
    <ul class="list-group" id="diy_sensor_list" style="display: none">
    <li class="list-group-item" id="diy_sensor_count" style="text-align: center"></li>
    </ul>
    </div>
    {#Actuator List#}
    <div class="list-area col-md-3 text-white py-5 py-md-0 pre-scrollable loading-2" id="actuator_div">
    <ul class="list-group" id="sosa_actuator_list" style="display: none">
    <li class="list-group-item" id="sosa_actuator_count" style="text-align: center"></li>
    </ul>
    <ul class="list-group" id="diy_actuator_list" style="display: none">
    <li class="list-group-item" id="diy_actuator_count" style="text-align: center"></li>
    </ul>
    </div>
    {#Rule List#}
    <div class="list-area col-md-6 text-white py-5 py-md-0 pre-scrollable loading-3" id="rule_div">
    <ul class="list-group" id="rule">
    </ul>
    </div>
</div>
    <footer class="row">
        <div class="footer col-md-12 text-white py-5 py-md-0">
        <a href="javascript:" onclick="self.location=document.referrer;">BACK</a>
        <span>Copyright © 2020 YICHEN WANG All rights reserved</span>
        </div>
    </footer>
</div>

{#   -----------------Index Page-------------------   #}

  <div class="masthead" id="input_area" style="display:block">
    <div class="masthead-bg" id="left_bg"></div>
{#    <div class="container h-100">#}
      <div class="row h-100">
        <div class="col-12 my-auto">
          <div class="masthead-content col-03 text-white py-5 py-md-0" id="inputbox">
            <div id="input_area">
                <div align="center"><img src={% static 'img/logo.png' %}></div>
            <h1 class="mb-3" style="text-align: center">ontospect</h1>
            <p class="mb-5">An automatic Toolchain for identifying
                <strong>Sensors, Actuators,</strong> and <strong>Logical Rules</strong> in IoT ontologies.</p>


            <form class="input-group input-group-newsletter" method="post" enctype="multipart/form-data">
                {% csrf_token  %}
                <input type="url" id="onto_url" class="form-control" placeholder="Enter URL or choose a local ontology file.">
                <div class="input-group-append">
                    <button class="btn btn-secondary" id="btn_url" type="button">START</button>
                </div>
            </form>
            <form  method="post" enctype="multipart/form-data">
                <p id ="textField"></p>
                {% csrf_token %}
                <input type='button' class='btn btn-secondary' value='SELECT' onclick="upload_file.click()" />
                <input type="file" name="filesource" id="upload_file" style="display: none" onchange="getFilePath()" />
                <button class="btn btn-secondary" id="btn_upload" type="button">UPLOAD</button>
            </form>
            </div>
          </div>
        </div>
{#      </div>#}
    </div>
  </div>


  <!-- Bootstrap core JavaScript -->
  <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/coming-soon.min.js' %} "></script>

</body>

</html>

<script>
function getFilePath() {
  var path = document.getElementById("upload_file").value;
  var name = path.substring(path.lastIndexOf('\\') + 1);
  document.getElementById("textField").innerHTML = "You Selected: " + name;
}
</script>